# Generated by Django 2.1.5 on 2019-02-10 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_date', models.DateTimeField()),
                ('published', models.BooleanField()),
                ('excluded', models.BooleanField()),
                ('src_channel', models.CharField(max_length=256)),
                ('categories', models.ManyToManyField(to='videosdb.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_id', models.CharField(max_length=256)),
                ('title', models.CharField(max_length=256)),
                ('filename', models.CharField(max_length=4096)),
                ('ipfs_hash', models.CharField(max_length=256)),
                ('ipfs_thumbnail_hash', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='VideoDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=4096)),
                ('uploader', models.CharField(max_length=256)),
                ('upload_date', models.CharField(max_length=256, null=True)),
                ('duration', models.IntegerField()),
                ('channel_url', models.CharField(max_length=1024, null=True)),
                ('uploader_url', models.CharField(max_length=256)),
                ('ext', models.CharField(max_length=256)),
                ('format', models.CharField(max_length=256)),
                ('format_note', models.CharField(max_length=256)),
                ('fulltitle', models.CharField(max_length=256)),
                ('width', models.IntegerField()),
                ('height', models.IntegerField()),
                ('view_count', models.IntegerField()),
                ('abr', models.IntegerField()),
                ('thumbnail', models.CharField(max_length=1024, null=True)),
                ('tags', models.ManyToManyField(to='videosdb.Tag')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videosdb.Video')),
            ],
        ),
        migrations.AddField(
            model_name='publication',
            name='tags',
            field=models.ManyToManyField(to='videosdb.Tag'),
        ),
        migrations.AddField(
            model_name='publication',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videosdb.Video'),
        ),
    ]
