# Generated by Django 2.1.5 on 2019-02-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videosdb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='publication',
            name='video',
        ),
        migrations.RemoveField(
            model_name='videodetails',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='videodetails',
            name='video',
        ),
        migrations.AddField(
            model_name='video',
            name='abr',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='categories',
            field=models.ManyToManyField(to='videosdb.Category'),
        ),
        migrations.AddField(
            model_name='video',
            name='channel_url',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='description',
            field=models.CharField(max_length=4096, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='excluded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='ext',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='format',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='format_note',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='fulltitle',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='post_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='publish_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='tags',
            field=models.ManyToManyField(to='videosdb.Tag'),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='upload_date',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='uploader',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='uploader_url',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='view_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='width',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(db_index=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='video',
            name='filename',
            field=models.CharField(max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='ipfs_hash',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='ipfs_thumbnail_hash',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='youtube_id',
            field=models.CharField(db_index=True, max_length=16),
        ),
        migrations.DeleteModel(
            name='Publication',
        ),
        migrations.DeleteModel(
            name='VideoDetails',
        ),
    ]
