# Generated by Django 2.1.5 on 2019-02-11 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videosdb', '0003_auto_20190211_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='thumbnail_url',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
