# Generated by Django 2.1.5 on 2019-02-11 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videosdb', '0005_video_channel_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
