# Generated by Django 2.2.13 on 2020-07-04 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videosdb', '0010_remove_video_thumbnail_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='description',
            field=models.CharField(max_length=4096, null=True),
        ),
    ]
