# Generated by Django 3.1.4 on 2020-12-23 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videosdb', '0013_video_sync_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='sync_action',
        ),
        migrations.AddField(
            model_name='video',
            name='yt_published_date',
            field=models.DateTimeField(null=True),
        ),
    ]
