# Generated by Django 3.1.4 on 2020-12-23 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videosdb', '0014_auto_20201223_0917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='ipfs_hash',
        ),
        migrations.RemoveField(
            model_name='video',
            name='ipfs_thumbnail_hash',
        ),
        migrations.RemoveField(
            model_name='video',
            name='published',
        ),
        migrations.RemoveField(
            model_name='video',
            name='thumbnail_id',
        ),
    ]
