# Generated by Django 3.1.4 on 2020-12-23 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videosdb', '0015_auto_20201223_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='post_id',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
