# Generated by Django 3.1.4 on 2020-12-24 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videosdb', '0017_auto_20201223_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='videosdb.video')),
                ('published_date', models.DateTimeField()),
                ('post_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='video',
            name='filename',
        ),
        migrations.RemoveField(
            model_name='video',
            name='post_id',
        ),
        migrations.RemoveField(
            model_name='video',
            name='published_date',
        ),
    ]
