# Generated by Django 3.1.4 on 2020-12-24 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videosdb', '0018_auto_20201224_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='published_date',
            field=models.DateTimeField(null=True),
        ),
    ]
