# Generated by Django 3.1.4 on 2020-12-25 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videosdb', '0020_auto_20201224_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
