# Generated by Django 3.1.4 on 2020-12-29 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videosdb', '0022_video_thumbnail_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='published_date',
            field=models.DateTimeField(null=True),
        ),
    ]
