# Generated by Django 3.1.4 on 2020-12-29 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videosdb', '0023_auto_20201229_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='post_id',
            field=models.IntegerField(null=True),
        ),
    ]
