# Generated by Django 3.1.4 on 2020-12-30 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videosdb', '0025_auto_20201229_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
