# Generated by Django 3.1.4 on 2020-12-30 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videosdb', '0026_video_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
