# Generated by Django 3.1.4 on 2021-01-03 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videosdb', '0027_auto_20201230_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='video',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
