# Generated by Django 3.1.4 on 2021-01-03 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videosdb', '0030_auto_20210103_2338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='slug',
        ),
        migrations.AddField(
            model_name='publication',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
