# Generated by Django 3.1.4 on 2021-01-06 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videosdb', '0031_auto_20210103_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='full_response',
            field=models.TextField(null=True),
        ),
    ]
