# Generated by Django 3.1.4 on 2021-01-06 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videosdb', '0033_auto_20210106_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=256, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(max_length=256, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='slug',
            field=models.SlugField(max_length=4096, null=True, unique=True),
        ),
    ]
