# Generated by Django 3.1.4 on 2021-01-11 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videosdb', '0036_auto_20210107_0224'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-yt_published_date']},
        ),
        migrations.RemoveIndex(
            model_name='category',
            name='category_slug_index',
        ),
        migrations.RemoveIndex(
            model_name='tag',
            name='tag_slug_index',
        ),
        migrations.RemoveIndex(
            model_name='video',
            name='youtube_id_index',
        ),
        migrations.RemoveIndex(
            model_name='video',
            name='slug_index',
        ),
    ]
