# Generated by Django 3.1.4 on 2021-01-13 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videosdb', '0037_auto_20210111_0159'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name']},
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug'], name='videosdb_ca_slug_4b462a_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['slug'], name='videosdb_ta_slug_83848a_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['youtube_id'], name='videosdb_vi_youtube_a742c5_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['slug'], name='videosdb_vi_slug_9616f2_idx'),
        ),
    ]
