# Generated by Django 3.1.5 on 2021-01-14 09:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videosdb', '0038_auto_20210113_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='videosdb.video')),
                ('published_date', models.DateTimeField(null=True)),
                ('post_id', models.IntegerField(null=True)),
                ('thumbnail_id', models.IntegerField(null=True)),
            ],
        ),
    ]
