# Generated by Django 3.1.5 on 2021-01-14 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videosdb', '0039_publication'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['id'], name='videosdb_vi_id_63dbbd_idx'),
        ),
    ]
