options:
    env:
        - BRANCH_NAME=$BRANCH_NAME
steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'echo $_DOCKER_PASSWORD | docker login --username eelis --password-stdin']

- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker pull gcr.io/$PROJECT_ID/$_IMAGE-$BRANCH_NAME:latest || exit 0']

- name: 'gcr.io/cloud-builders/docker'
  dir: "$_IMAGE"
  args: [
            'build',
            '-t', 'gcr.io/$PROJECT_ID/$_IMAGE-$BRANCH_NAME:$COMMIT_SHA',
            '-t', 'gcr.io/$PROJECT_ID/$_IMAGE-$BRANCH_NAME:latest',
            '--cache-from', 'gcr.io/$PROJECT_ID/$_IMAGE-$BRANCH_NAME:latest',
            '.'
        ]

- id: unittests
  name: docker
  args:
    - run
    - gcr.io/worpdress-279321/frontend-$BRANCH_NAME
    - yarn
    - test

timeout: 3600s
images: ['gcr.io/$PROJECT_ID/$_IMAGE-$BRANCH_NAME:latest', "gcr.io/$PROJECT_ID/$_IMAGE-$BRANCH_NAME:$COMMIT_SHA"]
