steps:

- name: node:latest
  dir: "frontend"
  entrypoint: "yarn"
  args: ["install"]

- name: node:latest
  dir: "frontend"
  env:
    - 'API_URL=$API_URL'
    - 'API_BROWSER_URL=$API_BROWSER_URL'  

  entrypoint: "yarn"  
  args: ["generate"]

- name: gcr.io/cloud-builders/gsutil
  args: ["-m", "rsync", "-r", "-c", "-d", "./dist", "gs://www.sadhguru.digital"]