steps:
 # Build and push the container image 
- name: 'gcr.io/kaniko-project/executor:v1.6.0'
  args:
  - --context=frontend
  - --destination=gcr.io/$PROJECT_ID/frontend:latest
  - --cache=true
  - --cache-ttl=360h

   