steps:
- id: check-for-new-videos
  waitFor: ["-"]
  name: docker
  args: ["run", "--rm", "-e", "DATABASE_URL=$_DATABASE_URL", "-e", "LOGLEVEL=INFO", "gcr.io/worpdress-279321/backend", 
    "poetry", "run", "python", "-O", 
    "manage.py", "videosdb", "--check-for-new-videos"]

 
- id: node-install-deps
  waitFor: ["-"]
  name: node:latest
  dir: "frontend"
  entrypoint: "yarn"
  args: ["install"]

- id: nuxt-generate
  waitFor: ["node-install-deps", "check-for-new-videos"]
  name: node:latest
  dir: "frontend"
  env:
    - 'API_URL=$_API_URL'
    - 'API_BROWSER_URL=$_API_BROWSER_URL'

  entrypoint: "yarn"  
  args: ["generate"]

- id: deploy-to-gs
  waitFor: ["nuxt-generate"]
  name: gcr.io/cloud-builders/gsutil
  dir: "frontend"
  args: ["-m", "-q", "rsync", "-r","-J", "-c", "-d", "./dist", "$_GS_BUCKET"]

timeout: 7200s