steps:

- name: node:latest
  dir: "frontend"
  entrypoint: "yarn"
  args: ["install"]

- name: node:latest
  dir: "frontend"
  env:
    - 'API_URL=$_API_URL'
    - 'API_BROWSER_URL=$_API_BROWSER_URL'

  entrypoint: "yarn"  
  args: ["generate"]

- name: gcr.io/cloud-builders/gsutil
  dir: "frontend"
  args: ["-m", "-q", "rsync", "-r","-J", "-c", "-d", "./dist", "$_GS_BUCKET"]

timeout: 7200s