steps:
 # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    dir: "frontend"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/frontend:latest", "."]
 # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/frontend:latest"]
    