version: 0.2

env:
  variables:
    TAG: "$CODEBUILD_RESOLVED_SOURCE_VERSION"
    REPO: "570555265801.dkr.ecr.ap-south-1.amazonaws.com/"
    DOCKER_BUILDKIT: 1
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 570555265801.dkr.ecr.ap-south-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker images...
      - docker buildx bake --push 
  post_build:
    commands:
      - echo Build completed on `date`