timeout: 7200s
options:
     env:
         - VIDEOSDB_CONFIG: $_VIDEOSDB_CONFIG
         - FIREBASE_PROJECT: $_FIREBASE_PROJECT
steps:
  - name: gcp.io/worpdress-279321/task
    args:
        - generate

