timeout: 5400s
steps:
  - name: us-central1-docker.pkg.dev/worpdress-279321/registry/videosdb-builder
    env:
        - 'BUILD_ID=$BUILD_ID'
        - 'VIDEOSDB_CONFIG=$_VIDEOSDB_CONFIG'
        - 'LOGLEVEL=$_LOGLEVEL'
    args:
        - --verbose
        - $TRIGGER_NAME

