steps:

  - id: check-for-new-videos
    name: docker
    args:
      - run
      - --rm
      - -e
      - LOGLEVEL=$_LOGLEVEL
      - --env-file
      - common/env/$_VIDEOSDB_CONFIG.txt
      - gcr.io/worpdress-279321/backend
      - -O
      - -m
      - videosdb
      - --check-for-new-videos


  - id: generate
    name: docker
    args:
      - run
      - --name
      - generate
      - --env-file
      - common/env/$_VIDEOSDB_CONFIG.txt
      - gcr.io/worpdress-279321/frontend
      - yarn
      - generate

  - id: copy
    name: docker
    args:
      - cp
      - generate:/src/dist
      - frontend/


  - name: gcr.io/worpdress-279321/firebase
    env:
      - 'GOOGLE_APPLICATION_CREDENTIALS=backend/videosdb/keys/$_VIDEOSDB_CONFIG.json'
    args:
      - deploy
      - --project
      - $_FIREBASE_PROJECT
      - --only=hosting

timeout: 5400s
