steps:

  - id: check-for-new-videos
    name: docker
    args: 
      - run
      - --rm
      - -e
      - LOGLEVEL=$_LOGLEVEL
      - gcr.io/worpdress-279321/backend
      - poetry
      - run
      - python
      - -O
      - -m
      - videosdb
      - --check-for-new-videos

  - id: generate
    name: docker
    args:
      - run
      - --name
      - generate
      - -e
      - DONT_USE_EMULATOR=1
      - gcr.io/worpdress-279321/frontend
      - yarn
      - generate

  - id: copy
    name: docker
    args:
      - cp
      - generate:/src/dist
      - frontend/


  - name: gcr.io/worpdress-279321/firebase
    args: 
      - deploy
      - --only=hosting

timeout: 7200s
