steps:

  - id: check-for-new-videos
    name: docker
    args: 
      - run
      - --rm
      - -e
      - DATABASE_URL=$_DATABASE_URL
      - -e
      - LOGLEVEL=$_LOGLEVEL
      - gcr.io/worpdress-279321/backend
      - poetry
      - run
      - python
      - -O
      - manage.py
      - videosdb
      - --check-for-new-videos

  - id: generate
    name: docker
    args:
      - run
      - --name
      - generate
      - -e
      - API_URL=$_API_URL
      - -e
      - API_BROWSER_URL=$_API_BROWSER_URL
      - gcr.io/worpdress-279321/frontend
      - yarn
      - generate

  - id: copy
    name: docker
    args:
      - cp
      - generate:/src/dist
      - frontend/


  - name: gcr.io/worpdress-279321/firebase
    args: 
      - deploy
      - --only=hosting

timeout: 7200s
