timeout: 5400s
options:
    env:
        - 'BUILD_ID=$BUILD_ID'
        - 'BRANCH_NAME=$BRANCH_NAME'
        - 'VIDEOSDB_CONFIG=$_VIDEOSDB_CONFIG'
        - 'LOGLEVEL=$_LOGLEVEL'
        - 'PROJECT_ID=$_PROJECT_ID'

steps:
  - name: us-central1-docker.pkg.dev/$_PROJECT_ID/registry/videosdb-builder
    args:
        - --verbose
        - init-gcp

  - name: us-central1-docker.pkg.dev/$_PROJECT_ID/registry/videosdb-builder
    args:
        - --verbose
        - $TRIGGER_NAME

