steps:

  - id: check-for-new-videos
    name: docker
    args:
      - run
      - --rm
      - --env-file
      - common/env/$_VIDEOSDB_CONFIG.txt
      - gcr.io/worpdress-279321/backend
      - --check-for-new-videos


  - id: generate
    name: docker
    args:
      - run
      - --name
      - generate
      - gcr.io/worpdress-279321/frontend
      - yarn
      - generate
      - --dotenv
      - common/env/$_VIDEOSDB_CONFIG.txt
    waitFor:

  - id: copy
    name: docker
    args:
      - cp
      - generate:/src/dist
      - frontend/


  - name: gcr.io/worpdress-279321/firebase
    env:
      - 'GOOGLE_APPLICATION_CREDENTIALS=backend/videosdb/creds.json'
    args:
      - deploy
      - --project
      - videosdb-$_VIDEOSDB_CONFIG
      - --only=hosting

timeout: 3600s
