steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'echo $_DOCKER_PASSWORD | docker login --username eelis --password-stdin']

- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker pull gcr.io/$PROJECT_ID/$_IMAGE-$BRANCH_NAME:latest || exit 0']

- name: 'gcr.io/cloud-builders/docker'
  dir: "$_IMAGE"
  args: [
            'build',
            '-t', 'gcr.io/$PROJECT_ID/$_IMAGE-$BRANCH_NAME:$COMMIT_SHA',
            '--cache-from', 'gcr.io/$PROJECT_ID/$_IMAGE-$BRANCH_NAME:latest',
            '.'
        ]

- name: 'gcr.io/cloud-builders/docker'
  args: ['tag',
            'gcr.io/$PROJECT_ID/$_IMAGE-$BRANCH_NAME:$COMMIT_SHA',
            'gcr.io/$PROJECT_ID/$_IMAGE-$BRANCH_NAME:latest']

images: ['gcr.io/$PROJECT_ID/$_IMAGE-$BRANCH_NAME:latest']
