wordpress_site_id: 156901386
wordpress_token: qpTIK7(hogZ#3WhSK#N@39xSQHc5aD@7D5VkxnXWBGgXsQwt90E#vw3!3yJA&Kc)
dns_zone: myzone
dnslink_name: videos.enlightenment.yoga
ipfs_gateway: ipfs.enlightenment.yoga
www_root: https://www.enlightenment.yoga
ipfs_host: localhost
ipfs_port: 5001
