dns_zone: spirituality
dnslink_name: resources.spiritualityresources.net
ipfs_gateway: ipfs.spiritualityresources.net
www_root: https://www.spiritualityresources.net
ipfs_host: localhost
ipfs_port: 5001
wp_username: dazzling-williams
wp_pass: DQLL7kfN8Sdj
youtube_key: AIzaSyBS_oLkjg3skPbC49VmPit3dPFPPnZDPRQ
youtube_channel:
    id: UCcYzLCs3zrQIBVHYA1sK2sw
    name: Sadhguru


    
