dns_zone: myzone
dnslink_name: resources.spiritualityresources.net
ipfs_gateway: ipfs.spiritualityresources.net
www_root: https://www.spiritualityresources.net
ipfs_host: localhost
ipfs_port: 5001
wp_username: sad-northcutt
wp_pass: MIwEvLhawMp0
