version: "3"
services:
    backend:
        network_mode: "host"
        image: ${REPO-}backend
        build:
            context: backend
        env_file: common/env/${VIDEOSDB_CONFIG-testing}.txt
        environment:
            - GOOGLE_CLOUD_PROJECT=${PROJECT-worpdress-279321}
        profiles:
            - none
        command: run main -c -e

    frontend:
        network_mode: "host"
        image: ${REPO-}frontend
        env_file: common/env/${VIDEOSDB_CONFIG-testing}.txt
        build:
            context: frontend
        depends_on:
            - firebase-emulator
        volumes:
            - yarn_cache:/yarn
        profiles:
            - none
        command: yarn generate

    # tests-end2end:
    #     depends_on:
    #         - firebase-emulator
    #         - json-caching-proxy
    #     command: "true"

    json-caching-proxy:
        network_mode: "host"
        image: ${REPO-}json-caching-proxy
        build:
            context: tests/end2end/utils/json-caching-proxy
        ports:
            - 43783:43783
        stop_signal: SIGKILL
        profiles:
            - end2end-tests

    firebase-emulator:
        network_mode: "host"
        image: ${REPO-}firebase-emulator
        environment:
            - GCP_PROJECT=${FIREBASE_PROJECT-firebase-testing}
            - ENABLE_UI=true
        volumes:
            - emulator-data:/firebase/baseline-data
        ports:
            - 8080:8080
        profiles:
            - tests
            - end2end-tests

    firebase:
        image: ${REPO-}firebase
        command: deploy --project ${FIREBASE_PROJECT-firebase-testing} --only=hosting
        profiles:
            - none

volumes:
    emulator-data:
        name: emulator-data
    yarn_cache:


