version: "3"
services:

    json-caching-proxy:
        image: ${REPO-}json-caching-proxy
        build:
            context: tests/end2end/utils/json-caching-proxy
            cache_from:
                - ${REPO-}json-caching-proxy
        ports:
            - 43783:43783
        stop_signal: SIGKILL

    firebase-emulator:
        image: ${REPO-}firebase-emulator
        build:
            context: tests/end2end/utils/firebase-emulator
            cache_from:
                - ${REPO-}firebase-emulator
        environment:
            - GCP_PROJECT=${FIREBASE_PROJECT-firebase-testing}
            - ENABLE_UI=true
        volumes:
            - emulator-data:/firebase/baseline-data
        ports:
            - 46456:46456

volumes:
    emulator-data:
        name: emulator-data
