version: "3"
services:
  db:
    image: ${REPO}db-latest
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    build:
      context: ./db
    ports:
      - 5433:5432
    restart: always

  backend-sadhguru:
    environment:
      - DJANGO_SETTINGS_MODULE=project.settings-sadhguru
    image: ${REPO}backend-latest
    links:
      - db
    build:
      context: ./backend
    ports:
      - 8001:8000
    volumes:
      - httplib_cache:/app/.cache
      - logs:/app/logs
    restart: always

  django-migrations-sadhguru:
    environment:
      - DJANGO_SETTINGS_MODULE=project.settings-sadhguru
    image: ${REPO}backend-latest
    command: poetry run python manage.py migrate --noinput
    links:
      - db

  frontend-sadhguru:
    environment:
      - API_URL=http://backend-sadhguru:8000
    image: ${REPO}frontend-latest
    links:
      - backend-sadhguru
    build:
      context: ./frontend
    ports:
      - 3001:3000
    restart: always

  backend-nithyananda:
    environment:
      - DJANGO_SETTINGS_MODULE=project.settings-nithyananda
    image: ${REPO}backend-latest
    links:
      - db
    build:
      context: ./backend
    ports:
      - 8002:8000
    volumes:
      - httplib_cache:/app/.cache
      - logs:/app/logs
    restart: always

  django-migrations-nithyananda:
    environment:
      - DJANGO_SETTINGS_MODULE=project.settings-nithyananda
    command: poetry run python manage.py migrate --noinput
    image: ${REPO}backend-latest
    links:
      - db

  frontend-nithyananda:
    environment:
      - API_URL=http://backend-nithyananda:8000
    image: ${REPO}frontend-latest
    links:
      - backend-nithyananda
    build:
      context: ./frontend
    ports:
      - 3002:3000
    restart: always

  # nginx:
  #   image: ${REPO}nginx-latest
  #   build:
  #     context: ./nginx
  #   restart: always
  #   depends_on:
  #     - frontend-nithyananda
  #     - frontend-sadhguru
  #   ports:
  #     - 8080:80

volumes:
  logs:
  httplib_cache:
