version: "3"
services:
    backend:
        network_mode: "host"
        image: ${REPO-}backend:${BRANCH_NAME-latest}
        build:
            context: backend
        env_file: common/env/${VIDEOSDB_CONFIG-testing}.txt
        environment:
            - GOOGLE_CLOUD_PROJECT=videosdb-testing
        profiles:
            - generate
            - end2end-tests
        command: run main -c -e

    backend-tests:
        network_mode: "host"
        image: ${REPO-}backend
        env_file: common/env/${VIDEOSDB_CONFIG-testing}.txt
        environment:
            - FIRESTORE_EMULATOR_HOST=localhost:8080
        command: run python -m unittest
        depends_on:
            - firestore-emulator
        profiles:
            - tests

    frontend:
        network_mode: "host"
        image: ${REPO-}frontend
        env_file: common/env/${VIDEOSDB_CONFIG-testing}.txt
        build:
            context: frontend
        depends_on:
            - firestore-emulator
        volumes:
            - yarn_cache:/yarn
        profiles:
            - generate
            - end2end-tests
        command: yarn generate

    frontend-tests:
        image: ${REPO-}frontend
        command: yarn test
        profiles:
            - tests

    # tests-end2end:
    #     depends_on:
    #         - firestore-emulator
    #         - json-caching-proxy
    #     command: "true"

    json-caching-proxy:
        network_mode: "host"
        image: ${REPO-}json-caching-proxy
        build:
            context: tests/end2end/utils/json-caching-proxy
        ports:
            - 43783:43783
        stop_signal: SIGKILL
        profiles:
            - "end2end-tests"

    firestore-emulator:
        network_mode: "host"
        image: spine3/firebase-emulator
        environment:
            - GCP_PROJECT=videosdb-testing
            - ENABLE_UI=true
        volumes:
            - emulator-data:/firebase/baseline-data
        ports:
            - 8080:8080
        profiles:
            - tests
            - end2end-tests

    firebase:
        image: gcr.io/worpdress-279321/firebase
        command: deploy --project ${FIREBASE_PROJECT-testing} --only=hosting
        profiles:
            - generate

volumes:
    emulator-data:
        name: emulator-data
    yarn_cache:


