version: "3"
services:
  db:
    image: gcr.io/worpdress-279321/videosdb-postgres:latest
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    build:
      context: .
      dockerfile: Dockerfile.postgres
    restart: always

  backend-sadhguru:
    environment:
      - DJANGO_SETTINGS_MODULE=project.settings-sadhguru
    image: gcr.io/worpdress-279321/videosdb-backend:latest
    links:
      - db
    build:
      context: ./backend
    ports:
      - 8001:8000
    volumes:
      - httplib_cache:/app/.cache
      - logs:/app/logs
    restart: always

  django-migrations-sadhguru:
    environment:
      - DJANGO_SETTINGS_MODULE=project.settings-sadhguru
    image: gcr.io/worpdress-279321/videosdb-backend:latest
    command: poetry run python manage.py migrate --noinput
    links:
      - db

  frontend-sadhguru:
    environment:
      - API_URL=http://backend-sadhguru:8000
      - VIDEOSDB_TITLE="Sadhguru wisdom"
      - VIDEOSDB_SUBTITLE="Mysticism, yoga, spirituality, day-to-day life tips, ancient wisdom, interviews, tales, and much more."
      - GCS_URL="https://cse.google.com/cse.js?cx=7c33eb2b1fc2db635"
    image: gcr.io/worpdress-279321/videosdb-frontend:latest
    links:
      - backend-sadhguru
    build:
      context: ./frontend
    ports:
      - 3001:3000
    restart: always

  backend-nithyananda:
    environment:
      - DJANGO_SETTINGS_MODULE=project.settings-nithyananda
    image: gcr.io/worpdress-279321/videosdb-backend:latest
    links:
      - db
    build:
      context: ./backend
    ports:
      - 8002:8000
    volumes:
      - httplib_cache:/app/.cache
      - logs:/app/logs
    restart: always

  django-migrations-nithyananda:
    environment:
      - DJANGO_SETTINGS_MODULE=project.settings-nithyananda
    command: poetry run python manage.py migrate --noinput
    image: gcr.io/worpdress-279321/videosdb-backend:latest
    links:
      - db

  frontend-nithyananda:
    environment:
      - API_URL=http://backend-nithyananda:8000
      - VIDEOSDB_TITLE="KAILASA's Nithyananda"
      - GCS_URL="https://cse.google.com/cse.js?cx=043c6e15fcd358d5a"
    image: gcr.io/worpdress-279321/videosdb-frontend:latest
    links:
      - backend-nithyananda
    build:
      context: ./frontend
    ports:
      - 3002:3000
    restart: always

volumes:
  logs:
  httplib_cache:
