version: "3.9"
services:

    json-caching-proxy:
        network_mode: "host"
        image: ${REPO-}json-caching-proxy
        build:
            context: tests/end2end/utils/json-caching-proxy
        ports:
            - 43783:43783
        stop_signal: SIGKILL
        stop_grace_period: 0s

    firebase-emulator:
        network_mode: "host"
        image: ${REPO-}firebase-emulator
        command: /root/entrypoint.sh --debug
        build:
            context: tests/end2end/utils/firebase-emulator
        environment:
            - GCP_PROJECT=${FIREBASE_PROJECT-firebase-testing}
            - ENABLE_UI=true
            - WSL_DISTRO_NAME=ubuntu
        ports:
            - 46456:46456
        stop_grace_period: 1m

    redis:
        network_mode: host
        image: redis:7
        ports:
            - 6379:6379
        command: redis-server --loglevel warning
        stop_grace_period: 1m

