services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  backend:
    image: videosdb_backend
    links:
      - db
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
  frontend:
    image: videosdb_frontend
    links:
      - backend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
