version: "3"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    restart: always
  backend:
    environment:
      - DJANGO_SETTINGS_MODULE=project.settings-sadhguru
    image: 570555265801.dkr.ecr.ap-south-1.amazonaws.com/videosdb:backend-latest
    links:
      - db
    build:
      context: ./backend
    ports:
      - 8000:8000
    restart: always
  django-migrations:
    environment:
      - DJANGO_SETTINGS_MODULE=project.settings-sadhguru
    image: 570555265801.dkr.ecr.ap-south-1.amazonaws.com/videosdb:backend-latest
    command: poetry run python manage.py migrate --noinput
    links:
      - db
  frontend:
    environment:
      - API_URL=http://backend:8000
    image: 570555265801.dkr.ecr.ap-south-1.amazonaws.com/videosdb:frontend-latest
    links:
      - backend
    build:
      context: ./frontend
    ports:
      - 3000:3000
    restart: always
