version: "3"
services:
  db:
    image: videosdb_postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    build:
      context: .
      dockerfile: Dockerfile.postgres
    restart: always

  backend-sadhguru:
    environment:
      - DJANGO_SETTINGS_MODULE=project.settings-sadhguru
    image: videosdb_backend
    links:
      - db
    build:
      context: ./backend
    ports:
      - 8001:8000
    restart: always

  django-migrations-sadhguru:
    environment:
      - DJANGO_SETTINGS_MODULE=project.settings-sadhguru
    image: videosdb_backend
    command: poetry run python manage.py migrate --noinput
    links:
      - db

  frontend-sadhguru:
    environment:
      - API_URL=http://backend-sadhguru:8000
      - VIDEOSDB_TITLE="Sadhguru wisdom"
      - VIDEOSDB_SUBTITLE="Mysticism, yoga, spirituality, day-to-day life tips, ancient wisdom, interviews, tales, and much more."
    image: videosdb_frontend
    links:
      - backend-sadhguru
    build:
      context: ./frontend
    ports:
      - 3001:3000
    restart: always

  backend-nithyananda:
    environment:
      - DJANGO_SETTINGS_MODULE=project.settings-nithyananda
    image: videosdb_backend
    links:
      - db
    build:
      context: ./backend
    ports:
      - 8002:8000
    restart: always

  django-migrations-nithyananda:
    environment:
      - DJANGO_SETTINGS_MODULE=project.settings-nithyananda
    image: videosdb_backend
    command: poetry run python manage.py migrate --noinput
    links:
      - db

  frontend-nithyananda:
    environment:
      - API_URL=http://backend-nithyananda:8000
      - VIDEOSDB_TITLE="KAILASA's Nithyananda"
    image: videosdb_frontend
    links:
      - backend-nithyananda
    build:
      context: ./frontend
    ports:
      - 3002:3000
    restart: always
