version: "3"
services:
  db:
    image: ${REPO}db:${TAG:-latest}
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=TBSV96364xXi2JeWZiVibnbGczFNg
    build:
      context: ./db
    ports:
      - 5432:5432
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      interval: 1h

  backend-sadhguru:
    image: ${REPO}backend:${TAG:-latest}

    environment:
      - DATABASE_URL=psql://postgres:TBSV96364xXi2JeWZiVibnbGczFNg@db:5432/postgres
      - TAG=${TAG}
      - PORT=8000
    links:
      - db
    build:
      context: ./backend
    ports:
      - 8000:8000
    volumes:
      - httplib_cache:/app/.cache
      - logs:/app/logs
    restart: unless-stopped
    healthcheck:
      interval: 1h

  nginx:
    image: ${REPO}nginx-backend:${TAG:-latest}
    restart: unless-stopped
    build:
      context: ./nginx
      dockerfile: Dockerfile.backend
    environment:
      - CERTBOT_EMAIL=xaum.io@gmail.com
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx_secrets:/etc/letsencrypt
      #- ./user_conf.d:/etc/nginx/user_conf.d
    links:
      - backend-sadhguru


  # frontend:
  #   image: ${REPO}frontend:${TAG:-latest}
  #   environment:
  #     - API_URL=http://backend-sadhguru:8000/api
  #     - API_BROWSER_URL=https://backend.sadhguru.digital/api  
  #   build:
  #     context: ./frontend

      

volumes:
  logs:
  httplib_cache:
  db:
  nginx_secrets:
