version: "3"
services:
  db:
    image: ${REPO}db:${TAG:-latest}
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=TBSV96364xXi2JeWZiVibnbGczFNg
    build:
      context: ./db
    ports:
      - 5431:5432
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      interval: 1h

  backend-sadhguru:
    image: ${REPO}backend:${TAG:-latest}

    environment:
      - DATABASE_URL=psql://postgres:TBSV96364xXi2JeWZiVibnbGczFNg@pgbouncer:5432/postgres
      - TAG=${TAG}
      - PORT=80
    links:
      - db
    build:
      context: ./backend
    ports:
      - 80:80
    volumes:
      - logs:/app/logs
    restart: unless-stopped
    healthcheck:
      interval: 1h

  nginx:
    image: ${REPO}nginx-backend:${TAG:-latest}
    restart: unless-stopped
    build:
      context: ./nginx
      dockerfile: Dockerfile.backend
    environment:
      - CERTBOT_EMAIL=xaum.io@gmail.com
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx_secrets:/etc/letsencrypt
    links:
      - backend-sadhguru


  pgbouncer:
    image: edoburu/pgbouncer
    environment:
      - DATABASE_URL=psql://postgres:TBSV96364xXi2JeWZiVibnbGczFNg@db:5432/postgres
    ports:
      - 5432:5432
    restart: unless-stopped
    links:
      - db
    healthcheck:
      interval: 1h      

volumes:
  logs:
  db:
  nginx_secrets:
