version: "3"
services:

  backend-sadhguru-fileserver:
    image: ${REPO}backend:${TAG:-latest}

    environment:
      - IPFS_HOST=ipfs
      - PYTHONWARNINGS=ignore
      - GRPC_DNS_RESOLVER=native
    build:
      context: ./backend
    entrypoint:
      [
        "nice",
        "-n",
        "20",
        "poetry",
        "run",
        "python",
        "-O",
        "-m",
        "videosdb",
        "--download-and-register-in-ipfs"
      ]
    volumes:
      - logs:/app/logs
      - /mnt/videos:/mnt/videos
    links:
      - ipfs

  ipfs:
    image: ${REPO}ipfs:${TAG:-latest}
    environment:
      - IPFS_PATH=/mnt/ipfs-repo
    build:
      context: ./ipfs
    ports:
      - 18080:18080
      - 5001:5001
      - 14001:14001
    volumes:
      - /mnt/videos:/mnt/videos
      - /mnt/ipfs-repo:/mnt/ipfs-repo
    restart: unless-stopped

  nginx:
    image: ${REPO}nginx-ipfs:${TAG:-latest}
    restart: unless-stopped
    build:
      context: ./nginx
      dockerfile: Dockerfile.ipfs
    environment:
      - CERTBOT_EMAIL=xaum.io@gmail.com
    ports:
      - 80:80
      - 443:443
    volumes:
      - nginx_secrets:/etc/letsencrypt
    links:
      - ipfs

volumes:
  nginx_secrets: null
  logs: null
