version: "3"
services:
  db:
    image: ${REPO}db${BRANCH}
    platform: linux/arm/v7
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    build:
      context: ./db
    ports:
      - 5432:5432
    restart: always

  backend-sadhguru:
    image: ${REPO}backend${BRANCH}

    platform: linux/arm/v7
    environment:
      - DJANGO_SETTINGS_MODULE=project.settings-sadhguru
    links:
      - db
    build:
      context: ./backend
    ports:
      - 8001:8000
    volumes:
      - httplib_cache:/app/.cache
      - logs:/tmp/
    restart: always

  django-migrations-sadhguru:
    platform: linux/arm/v7
    image: ${REPO}backend${BRANCH}

    environment:
      - DJANGO_SETTINGS_MODULE=project.settings-sadhguru
    command: poetry run python manage.py migrate --noinput
    links:
      - db

  frontend-sadhguru:
    platform: linux/arm/v7
    image: ${REPO}frontend${BRANCH}

    environment:
      - API_URL=http://backend-sadhguru:8000
    links:
      - backend-sadhguru
    build:
      context: ./frontend
    ports:
      - 3001:3000
    restart: always


volumes:
  logs:
  httplib_cache:
