version: '3'
env:
    DOCKER_PASSWORD: 5@fs@i@58Zp6wfiH
    REPO_PROJECT: worpdress-279321
    REPO: '{{if .BUILD_ID }}gcr.io/{{.REPO_PROJECT}}/{{end}}'
    FIRESTORE_EMULATOR_HOST: 127.0.0.1:46456
    YOUTUBE_API_URL: http://127.0.0.1:43783/youtube/v3
    BRANCH:
        sh: git branch --show-current
    REVISION_ID:
        sh: git rev-parse HEAD

output: prefixed

tasks:
    init:
        internal: true
        run: once
        cmds:
            - cmd:
                '{{if .BUILD_ID }}
                    echo {{.DOCKER_PASSWORD}} | docker login --username eelis --password-stdin;
                    docker login gcr.io
                {{else}}
                    pgrep docker > /dev/null || sudo service docker start
                {{end}}'

    build:
        internal: true
        cmds:
            # pull the image for --cache-from
            - cmd: '{{if .BUILD_ID }} docker pull -q {{.REPO}}{{.IMAGE}}-{{.BRANCH}}:latest{{end}}'
              ignore_errors: true

            - docker build
                -t {{.REPO}}{{.IMAGE}}-{{.BRANCH}}:{{.REVISION_ID}}
                -t {{.REPO}}{{.IMAGE}}-{{.BRANCH}}:latest
                --cache-from {{.REPO}}{{.IMAGE}}-{{.BRANCH}}:latest
                {{.IMAGE}}


    wait-for-emulator:
        internal: true
        cmds:
            - docker run --rm --network host busybox
                sh -c '
                    until nc -z {{.FIRESTORE_EMULATOR_HOST | replace ":" " "}};
                        do echo "waiting for emulator...";
                        sleep 1;
                    done'

    build-backend:
        deps: [init]
        run: once
        cmds:
            - cp -r common backend
            - task: build
              vars:
                IMAGE: backend

    build-frontend:
        deps: [init]
        run: once
        cmds:
            - cp -r common frontend
            # firebase command needs this file here:
            - cp common/firebase/firebase.json frontend
            - task: build
              vars:
                IMAGE: frontend

    build-all:
        deps: [build-frontend, build-backend]

    start-test-servers:
        deps: [init]
        run: once
        cmds:
            - '{{if .BUILD_ID }}
                    docker compose pull -q
                {{else}}
                    docker compose build
                {{end}}'
            - docker compose stop
            - docker compose up --detach
            - task: wait-for-emulator

    stop-test-servers: docker compose down

    unittests-frontend:
        run: once
        deps:  [init, build-frontend]
        cmds:
            - docker run --rm
                --network host
                --env-file common/env/testing.txt
                {{.REPO}}frontend-{{.BRANCH}}:latest  yarn test


    unittests-backend:
        run: once
        deps: [init, build-backend, start-test-servers]
        cmds:
            - docker run --rm
                --network host
                --env-file common/env/testing.txt
                -e LOGLEVEL=DEBUG
                -e DEBUG=1
                -e PYTHONDEVMODE=1
                -e FIRESTORE_EMULATOR_HOST={{.FIRESTORE_EMULATOR_HOST}}
                {{.REPO}}backend-{{.BRANCH}}:latest
                run sh -c "coverage run -m unittest && coverage report -m && coverage html"


    unittests:
        run: once
        deps: [init, unittests-backend, unittests-frontend]

    end2end-tests:
        run: once
        deps: [init, build-frontend, build-backend, start-test-servers]
        cmds:
            - defer: docker compose logs
            - mkdir -p .httpx-cache
            - docker run --rm
                --network host
                --env-file common/env/testing.txt
                -e LOGLEVEL=DEBUG
                -e DEBUG=1
                -e PYTHONDEVMODE=1
                -e FIRESTORE_EMULATOR_HOST={{.FIRESTORE_EMULATOR_HOST}}
                -e YOUTUBE_API_URL={{.YOUTUBE_API_URL}}
                {{.REPO}}backend-{{.BRANCH}}:latest
                run main -c -e

            - docker run --rm
                --network host
                --env-file common/env/testing.txt
                -e FIRESTORE_EMULATOR_HOST={{.FIRESTORE_EMULATOR_HOST}}
                {{.REPO}}frontend-{{.BRANCH}}:latest
                {{if .BUILD_ID }}
                    yarn generate
                {{else}}
                    yarn run-s generate start
                {{end}}


    deploy-test:
        run: once
        deps: [init, build-frontend, build-backend, start-test-servers]
        cmds:
            - docker run
                --network host
                -e YOUTUBE_API_URL={{.YOUTUBE_API_URL}}
                -e FIRESTORE_EMULATOR_HOST={{.FIRESTORE_EMULATOR_HOST}}
                --env-file common/env/{{.VIDEOSDB_CONFIG}}.txt
                {{.REPO}}backend-{{.BRANCH}}:latest
                run main -c -e

            - docker run
                --network host
                --env-file common/env/{{.VIDEOSDB_CONFIG}}.txt
                -e GOOGLE_APPLICATION_CREDENTIALS=common/keys/{{.VIDEOSDB_CONFIG}}.json
                {{.REPO}}frontend-{{.BRANCH}}:latest
                yarn run-s generate deploy

    download-cache:
        deps: [init]
        cmds:
            - docker run --rm
                -v $(pwd)/common/keys:/keys
                google/cloud-sdk:alpine
                gcloud auth activate-service-account --key-file /keys/{{.VIDEOSDB_CONFIG}}.json &&
                gsutil cp gs://httpx-cache-{{.VIDEOSDB_CONFIG}}/cache.tar.gz .
            - rm -fr .httpx-cache
            - tar xf cache.tar.gz
            - rm cache.tar.gz



    upload-cache:
        deps: [init]
        cmds:
            - rm -f cache.tar.gz
            - tar czf cache.tar.gz .httpx-cache
            - docker run --rm
                -v $(pwd)/common/keys:/keys
                google/cloud-sdk:alpine
                gcloud auth activate-service-account --key-file /keys/{{.VIDEOSDB_CONFIG}}.json &&
                gsutil cp cache.tar.gz gs://httpx-cache-{{.VIDEOSDB_CONFIG}}
            - rm cache.tar.gz

    prueba:
        cmds:
            - task: "{{if .PRUEBA_YES}}init{{end}}"

    generate:
        run: once
        deps: [init, build-frontend, build-backend, unittests, end2end-tests]
        cmds:
            - task: "{{if .BUILD_ID}}download-cache{{end}}"
              vars:
                VIDEOSDB_CONFIG: {{.VIDEOSDB_CONFIG}}

            - mkdir -p .httpx-cache
            - docker run --rm
                --name backend
                --network host
                --mount type=bind,src=$(pwd)/.httpx-cache,dst=/root/.cache/httpx-cache
                --env-file common/env/{{.VIDEOSDB_CONFIG}}.txt
                {{.REPO}}backend-{{.BRANCH}}:latest
                run main
                    --check-for-new-videos
                    --enable-twitter-publishing
            - task: "{{if .BUILD_ID}}upload-cache{{end}}"
              vars:
                VIDEOSDB_CONFIG: {{.VIDEOSDB_CONFIG}}

            - docker run --rm
                --name frontend
                --network host
                --env-file common/env/{{.VIDEOSDB_CONFIG}}.txt
                -e GOOGLE_APPLICATION_CREDENTIALS=common/keys/{{.VIDEOSDB_CONFIG}}.json
                {{.REPO}}frontend-{{.BRANCH}}:latest
                yarn run-s generate deploy


    push:
        deps: [init]
        internal: true
        cmds:
            - docker push -q {{.REPO}}{{.IMAGE}}-{{.BRANCH}}:{{.REVISION_ID}}
            - docker push -q {{.REPO}}{{.IMAGE}}-{{.BRANCH}}:latest


    push-frontend:
        deps: [build-frontend]
        run: once
        cmds:
            - task: push
              vars:
                IMAGE: frontend


    push-backend:
        deps: [build-backend]
        run: once
        cmds:
            - task: push
              vars:
                IMAGE: backend

    build-and-push-test-servers:
        deps: [init]
        run: once
        cmds:
            - REPO={{.REPO}} docker compose build
            - docker login gcr.io
            - REPO={{.REPO}} docker compose push
        vars:
            REPO: gcr.io/{{.REPO_PROJECT}}/


    default:
        deps: [init, build-all, unittests, end2end-tests]

# cloud build trigger tasks. Task names must match with the trigger names in the GCP console

    backend-master:
        deps: [init, build-backend, unittests-backend]
        cmds:
            - task: push-backend

    backend-prod:
        deps: [build-backend, unittests-backend, end2end-tests]
        cmds:
            - task: push-backend

    frontend-master:
        deps: [build-frontend, unittests-frontend]
        cmds:
            - task: push-frontend

    frontend-prod:
        deps: [build-frontend, unittests-frontend, end2end-tests]
        cmds:
            - task: push-frontend

    tests-end2end-master:
        cmds:
            - task: end2end-tests

    tests-end2end-prod:
        cmds:
            - task: end2end-tests

    generate-testing:
        - task: generate
          vars:
            VIDEOSDB_CONFIG: testing
            FIREBASE_PROJECT: videosdb-testing

    generate-sadhguru:
        - task: generate
          vars:
            VIDEOSDB_CONFIG: sadhguru
            FIREBASE_PROJECT: videosdb-firebase

    generate-nithyananda:
        - task: generate
          vars:
            VIDEOSDB_CONFIG: nithyananda
            FIREBASE_PROJECT: videosdb-nithyananda

