version: '3'
env:
    DOCKER_PASSWORD: 5@fs@i@58Zp6wfiH
    MAIN_PROJECT: worpdress-279321
    REGISTRY: us-central1-docker.pkg.dev/{{.MAIN_PROJECT}}/registry/
    REPO: '{{if .IN_GCP }}{{.REGISTRY}}{{end}}'
    FIRESTORE_EMULATOR: 127.0.0.1:46456
    YOUTUBE_API_URL: http://127.0.0.1:43783/youtube/v3
    IN_GCP: "{{.BUILD_ID}} || {{.GOOGLE_CLOUD_SHELL}}"
    BRANCH:
        sh: git branch --show-current
    REVISION_ID:
        sh: git rev-parse HEAD
    TEST_SERVERS: json-caching-proxy firebase-emulator

output: prefixed

tasks:
    init:
        run: once
        cmds:
            - cmd:
                '{{if .IN_GCP }}
                    echo {{.DOCKER_PASSWORD}} | docker login --username eelis --password-stdin;
                    gcloud auth activate-service-account --key-file common/keys/{{.MAIN_PROJECT}}.json;
                    gcloud auth configure-docker us-central1-docker.pkg.dev --quiet
                {{end}}'
            - env

    build:
        internal: true
        cmds:
            # pull the image for --cache-from
            - cmd: '{{if .IN_GCP }} docker pull -q {{.REPO}}{{.IMAGE}}-{{.BRANCH}}:latest{{end}}'
              ignore_error: true

            - docker build
                -t {{.REPO}}{{.IMAGE}}-{{.BRANCH}}:{{.REVISION_ID}}
                -t {{.REPO}}{{.IMAGE}}-{{.BRANCH}}:latest
                --cache-from {{.REPO}}{{.IMAGE}}-{{.BRANCH}}:latest
                {{.IMAGE}}


    wait-for-port:
        internal: true
        cmds:
            - docker run --rm --network host busybox
                sh -c '
                    until nc -z {{.HOST}} {{.PORT}};
                        do echo "waiting for port {{.PORT}} on host {{.HOST}} ...";
                        sleep 2;
                    done'

    build-backend:
        deps: [init]
        run: once
        cmds:
            - cp -r common backend
            - task: build
              vars:
                IMAGE: backend

    build-frontend:
        deps: [init]
        run: once
        cmds:
            - cp -r common frontend
            # firebase command needs this file here:
            - cp common/firebase/firebase.json frontend
            - task: build
              vars:
                IMAGE: frontend

    build-all:
        deps: [build-frontend, build-backend]

    wait-for-redis:
        cmds:
            - task: wait-for-port
              vars:
                HOST: 127.0.0.1
                PORT: 6379

    wait-for-emulator:
        cmds:
            - task: wait-for-port
              vars:
                HOST:
                    sh: echo {{.FIRESTORE_EMULATOR}} | cut -d ":" -f 1
                PORT:
                    sh: echo {{.FIRESTORE_EMULATOR}} | cut -d ":" -f 2


    start-servers:
        deps: [init]
        run: once
        cmds:
            - '{{if .IN_GCP }}
                    docker compose pull -q
                {{else}}
                    docker compose build
                {{end}}'
            - docker compose restart
            - docker compose up --detach
            - task: wait-for-redis
            - task: wait-for-emulator

    stop-servers: docker compose down

    unittests-frontend:
        run: once
        deps:  [init, build-frontend]
        cmds:
            - docker run --rm
                --network host
                --env-file common/env/testing.txt
                {{.REPO}}frontend-{{.BRANCH}}:latest
                yarn test


    unittests-backend:
        run: once
        deps: [init, build-backend, start-servers]
        cmds:
            - rm -f {{.CID_FILE}}
            - docker run
                --cidfile {{.CID_FILE}}
                --network host
                --env-file common/env/testing.txt
                -e LOGLEVEL=DEBUG
                -e DEBUG=1
                -e PYTHONDEVMODE=1
                -e FIRESTORE_EMULATOR_HOST={{.FIRESTORE_EMULATOR}}
                {{.REPO}}backend-{{.BRANCH}}:latest
                run sh -c "coverage run -m unittest && coverage report -m && coverage html"
            - defer: docker rm $(cat {{.CID_FILE}})
            - docker cp $(cat {{.CID_FILE}}):/app/htmlcov .
        vars:
            CID_FILE: /tmp/unittests-backend.cid

    unittests:
        run: once
        deps: [init, unittests-backend, unittests-frontend]

    end2end-tests:
        run: once
        deps: [init, build-frontend, build-backend, start-servers]
        cmds:
            #- defer: docker compose logs
            - docker run --rm
                --network host
                --env-file common/env/testing.txt
                -e LOGLEVEL=DEBUG
                -e DEBUG=1
                -e PYTHONDEVMODE=1
                -e FIRESTORE_EMULATOR_HOST={{.FIRESTORE_EMULATOR}}
                -e YOUTUBE_API_URL={{.YOUTUBE_API_URL}}
                {{.REPO}}backend-{{.BRANCH}}:latest
                run main -c

            - docker run --rm
                --network host
                --env-file common/env/testing.txt
                -e FIRESTORE_EMULATOR_HOST={{.FIRESTORE_EMULATOR}}
                {{.REPO}}frontend-{{.BRANCH}}:latest
                {{if .IN_GCP }}
                    yarn generate
                {{else}}
                    yarn run-s generate start
                {{end}}


    # deploy-test:
    #     run: once
    #     deps: [init, build-frontend, build-backend, start-servers]
    #     cmds:
    #         - docker run
    #             --network host
    #             -e YOUTUBE_API_URL={{.YOUTUBE_API_URL}}
    #             -e FIRESTORE_EMULATOR_HOST={{.FIRESTORE_EMULATOR}}
    #             --env-file common/env/{{.VIDEOSDB_CONFIG}}.txt
    #             {{.REPO}}backend-{{.BRANCH}}:latest
    #             run main -c

    #         - docker run
    #             --network host
    #             --env-file common/env/{{.VIDEOSDB_CONFIG}}.txt
    #             -e GOOGLE_APPLICATION_CREDENTIALS=common/keys/{{.VIDEOSDB_CONFIG}}.json
    #             {{.REPO}}frontend-{{.BRANCH}}:latest
    #             yarn run-s generate deploy

    download-cache:
        deps: [init]
        cmds:
            - gsutil cp gs://httpx-cache-{{.VIDEOSDB_CONFIG}}/dump.rdb.gz .
            - gunzip -f dump.rdb.gz


    upload-cache:
        deps: [init]
        cmds:
            - gzip --keep dump.rdb
            - gsutil cp dump.rdb.gz gs://httpx-cache-{{.VIDEOSDB_CONFIG}}/
            - rm -f dump.rdb.gz


    run-backend:
        run: once
        deps: [init, build-backend]
        cmds:
            - docker compose stop redis
            - docker compose cp dump.rdb redis:/data
            - docker compose up redis -d
            - task: wait-for-redis
            - defer: docker compose stop redis && docker compose cp redis:/data/dump.rdb .
            - docker compose restart firebase-emulator
            - task: wait-for-emulator
            - docker run --rm
                --network host
                --env-file common/env/{{.VIDEOSDB_CONFIG}}.txt
                {{if .LOGLEVEL}} -e LOGLEVEL={{.LOGLEVEL}} {{end}}
                {{.REPO}}backend-{{.BRANCH}}:latest
                run main
                    --check-for-new-videos
                    --enable-transcripts
                    --enable-twitter-publishing
                    --export-to-emulator-host {{.FIRESTORE_EMULATOR}}



    run-frontend:
        run: once
        deps: [init, build-frontend]
        cmds:
            - docker run --rm
                --network host
                --env-file common/env/{{.VIDEOSDB_CONFIG}}.txt
                -e FIRESTORE_EMULATOR_HOST={{.FIRESTORE_EMULATOR}}
                -e GOOGLE_APPLICATION_CREDENTIALS=common/keys/{{.VIDEOSDB_CONFIG}}.json
                {{.REPO}}frontend-{{.BRANCH}}:latest
                yarn run-s generate deploy



    generate-gcp:
        deps: [init,  build-all, unittests, end2end-tests, download-cache]
        cmds:
            - task: generate
            - defer: {task: upload-cache}



    generate:
        deps: [init, build-all, unittests, end2end-tests, start-servers]
        cmds:
            - task: run-backend
            - task: run-frontend



    push:
        deps: [init]
        internal: true
        cmds:
            - docker push -q {{.REPO}}{{.IMAGE}}-{{.BRANCH}}:{{.REVISION_ID}}
            - docker push -q {{.REPO}}{{.IMAGE}}-{{.BRANCH}}:latest


    push-frontend:
        deps: [build-frontend]
        run: once
        cmds:
            - task: push
              vars:
                IMAGE: frontend


    push-backend:
        deps: [build-backend]
        run: once
        cmds:
            - task: push
              vars:
                IMAGE: backend

    build-and-push-other-images:
        deps: [init]
        run: once
        cmds:
            - REPO={{.REGISTRY}} docker compose build {{.TEST_SERVERS}}
            - REPO={{.REGISTRY}} docker compose push {{.TEST_SERVERS}}
            - docker build utils/builder -t {{.REGISTRY}}videosdb-builder
            - docker push {{.REGISTRY}}videosdb-builder
        vars:
            IN_GCP: dummy-build-id


    test:
        deps: [init, unittests, end2end-tests]

    default:
        deps: [init, build-all, unittests, end2end-tests]


    local-run-backend:
        cd backend &&
        LOGLEVEL=DEBUG
        DEBUG=1
        YOUTUBE_API_URL=http://127.0.0.1:43783/youtube/v3
        FIRESTORE_EMULATOR_HOST=localhost:46456
        poetry run main -c --dotenv ../common/env/testing.txt; cd ..

    local-ipython-shell: backend/utils/ipythonshell.sh




# cloud build trigger tasks. Task names must match with the trigger names in the GCP console

    backend-master:
        deps: [init, build-backend, unittests-backend]
        cmds:
            - task: push-backend

    backend-prod:
        deps: [build-backend, unittests-backend, end2end-tests]
        cmds:
            - task: push-backend

    frontend-master:
        deps: [build-frontend, unittests-frontend]
        cmds:
            - task: push-frontend

    frontend-prod:
        deps: [build-frontend, unittests-frontend, end2end-tests]
        cmds:
            - task: push-frontend

    tests-end2end-master:
        cmds:
            - task: end2end-tests

    tests-end2end-prod:
        cmds:
            - task: end2end-tests

    generate-testing:
        cmds:
            - task: generate-gcp
        preconditions:
            - test {{.VIDEOSDB_CONFIG}}

    generate-sadhguru:
        cmds:
            - task: generate-gcp
        preconditions:
            - test {{.VIDEOSDB_CONFIG}}

    generate-nithyananda:
        cmds:
            - task: generate-gcp
        preconditions:
            - test {{.VIDEOSDB_CONFIG}}

