version: '3'
env:
    DOCKER_PASSWORD: 5@fs@i@58Zp6wfiH
    REPO_PROJECT: worpdress-279321
    REPO: '{{if empty .BRANCH_NAME }}{{else}}grc.io/{{.REPO_PROJECT}}/{{.BRANCH_NAME}}/{{end}}'
tasks:
    init-local:
        cmds:
            - pgrep docker > /dev/null || sudo service docker start

    init-gcp:
        cmds:
            - echo $DOCKER_PASSWORD | docker login --username eelis --password-stdin
        preconditions:
            - .REPO

    backend: docker compose build --pull backend

    frontend: docker compose build --pull frontend

    firebase: docker compose build --pull firebase

    start-test-servers:
        cmds:
            - docker compose  build --pull firebase-emulator json-caching-proxy
            - docker compose up --detach firebase-emulator json-caching-proxy


    frontend-unittests:
        deps:  [frontend]
        cmds:
            - docker compose run frontend yarn test

    backend-unittests:
        deps:  [start-test-servers, backend]
        cmds:
            - docker compose run
                -e FIRESTORE_EMULATOR_HOST=localhost:8080
                backend run python -m unittest

    unittests:
        deps: [backend-unittests, frontend-unittests]

    end2end-tests:
        depends: [frontend-unittests, backend-unittests, start-test-servers]
        cmds:
            - docker compose up json-caching-proxy firebase-emulator --detach
            - docker compose run backend run main -c -e
            - docker compose run frontend yarn generate


    generate:
        deps: [frontend, backend, firebase]
        cmds:
            - docker compose run backend run main --check-for-new-videos
            - docker compose run --name generate frontend yarn generate
            - docker cp generate:/app/dist frontend/
            - docker compose run
                -e GOOGLE_APPLICATION_CREDENTIALS=backend/videosdb/keys/$VIDEOSDB_CONFIG.json
                firebase deploy
                --project ${FIREBASE_PROJECT}
                --only=hosting

    push:
        preconditions:
            - .REPO
        cmds:
             - docker compose push {{.IMAGE}}





