version: '3'
env:
    DOCKER_PASSWORD: 5@fs@i@58Zp6wfiH
    MAIN_PROJECT: worpdress-279321
    REGISTRY: us-central1-docker.pkg.dev/{{.MAIN_PROJECT}}/registry/
    REPO: '{{if .BUILD_ID }}{{.REGISTRY}}{{end}}'
    FIRESTORE_EMULATOR: 127.0.0.1:46456
    YOUTUBE_API_URL: http://127.0.0.1:43783/youtube/v3
    REVISION_ID:
        sh: echo ${REVISION_ID:-$(git rev-parse HEAD)}
    TEST_SERVERS: json-caching-proxy firebase-emulator
    BRANCH_NAME:
        sh: echo ${BRANCH_NAME:-$(git branch --show-current)}
    NODE_OPTIONS: --openssl-legacy-provider

output: prefixed


# WARNING: parallelization of tasks unittests-backend and end2end-tests task
# may result in unexpected test results (due to the same tests sharing the same DB instance).


tasks:
    init-gcp:
        run: once
        cmds:
            - env
            - echo {{.DOCKER_PASSWORD}} | docker login --username eelis --password-stdin;
            - gcloud auth activate-service-account --key-file common/keys/{{.MAIN_PROJECT}}.json;
            - gcloud auth configure-docker us-central1-docker.pkg.dev --quiet
            # - git clone --depth 1 git@github.com:kovan/videosdb
            # - git checkout $BRANCH_NAME

    build:
        internal: true
        cmds:
            - date
            # pull the image for --cache-from
            - cmd: '{{if .BUILD_ID }} docker pull -q {{.REPO}}{{.IMAGE}}-{{.BRANCH_NAME}}:latest{{end}}'
              ignore_error: true

            - docker build
                -t {{.REPO}}{{.IMAGE}}-{{.BRANCH_NAME}}:{{.REVISION_ID}}
                -t {{.REPO}}{{.IMAGE}}-{{.BRANCH_NAME}}:latest
                --cache-from {{.REPO}}{{.IMAGE}}-{{.BRANCH_NAME}}:latest
                {{.IMAGE}}


    wait-for-port:
        internal: true
        cmds:
            - docker run --rm --network host busybox
                sh -c '
                    until nc -z {{.HOST}} {{.PORT}};
                        do echo "waiting for port {{.PORT}} on host {{.HOST}} ...";
                        sleep 2;
                    done; sleep 1;'

    build-backend:
        run: once
        cmds:
            - cp -r common backend
            - task: build
              vars:
                IMAGE: backend

    build-frontend:
        run: once
        cmds:
            - cp -r common frontend
            # firebase command needs this file here:
            - cp common/firebase/firebase.json frontend
            - task: build
              vars:
                IMAGE: frontend

    build-all:
        deps: [build-frontend, build-backend]

    wait-for-redis:
        cmds:
            - task: wait-for-port
              vars:
                HOST: 127.0.0.1
                PORT: 6379

    wait-for-emulator:
        cmds:
            - task: wait-for-port
              vars:
                HOST:
                    sh: echo {{.FIRESTORE_EMULATOR}} | cut -d ":" -f 1
                PORT:
                    sh: echo {{.FIRESTORE_EMULATOR}} | cut -d ":" -f 2


    prepare-servers:
        run: once
        cmds:
            - date
            - '{{if .BUILD_ID }}
                    docker compose pull -q
                {{else}}
                    docker compose build
                {{end}}'
            - docker compose create

    stop-servers: docker compose down

    unittests-frontend:
        run: once
        deps:  [build-frontend]
        cmds:
            - date
            - docker run --rm
                --network host
                --env-file common/env/testing.txt
                {{.REPO}}frontend-{{.BRANCH_NAME}}:latest
                yarn test



    unittests-backend:
        run: once
        deps: [build-backend, prepare-servers]
        cmds:
            - date
            - docker compose restart firebase-emulator redis
            - task: wait-for-emulator
            - rm -f {{.CID_FILE}}
            - docker run
                --cidfile {{.CID_FILE}}
                --network host
                -e LOGLEVEL=DEBUG
                -e PYTHONDEVMODE=1
                -e FIRESTORE_EMULATOR_HOST={{.FIRESTORE_EMULATOR}}
                {{.REPO}}backend-{{.BRANCH_NAME}}:latest
                run sh -c "coverage run -m unittest && coverage report -m && coverage html"
            - defer: docker rm $(cat {{.CID_FILE}})
            - docker cp $(cat {{.CID_FILE}}):/app/htmlcov .
        vars:
            CID_FILE: /tmp/unittests-backend.cid

    unittests:
        run: once
        deps: [unittests-backend, unittests-frontend]

    end2end-tests:
        run: once
        deps: [build-frontend, build-backend, prepare-servers]
        cmds:
            - date
            - docker compose restart firebase-emulator redis json-caching-proxy
            - task: wait-for-emulator
            - task: tail-servers-logs
            - docker run --rm
                --network host
                --env-file common/env/testing.txt
                -e LOGLEVEL=DEBUG
                -e DEBUG=1
                -e PYTHONDEVMODE=1
                -e FIRESTORE_EMULATOR_HOST={{.FIRESTORE_EMULATOR}}
                -e YOUTUBE_API_URL={{.YOUTUBE_API_URL}}
                -e YOUTUBE_CHANNEL_ID=UCcYzLCs3zrQIBVHYA1sK2sw
                {{.REPO}}backend-{{.BRANCH_NAME}}:latest
                run main -c

            - docker run --rm
                --network host
                --env-file common/env/testing.txt
                -e FIRESTORE_EMULATOR_HOST={{.FIRESTORE_EMULATOR}}
                {{.REPO}}frontend-{{.BRANCH_NAME}}:latest
                yarn run-s generate {{if .START_DEV_SERVER}}start{{end}}

    tail-servers-logs: (docker compose logs -f -t --no-color | grep -v "Detected non-HTTP/2 connection"  | grep -v HttpVersionRoutingHandler ) &

    download-cache:
        cmds:
            - gsutil cp gs://httpx-cache-{{.VIDEOSDB_CONFIG}}/dump.rdb.gz .
            - gunzip -f dump.rdb.gz


    upload-cache:
        cmds:
            - gzip -f --keep dump.rdb
            - gsutil cp dump.rdb.gz gs://httpx-cache-{{.VIDEOSDB_CONFIG}}/
            - rm -f dump.rdb.gz


    run-backend:
        deps: [prepare-servers]
        run: once
        cmds:
            - date
            - docker compose stop
            - docker compose cp dump.rdb redis:/data
            - docker compose start firebase-emulator redis
            - task: wait-for-emulator
            - defer: docker compose stop redis && docker compose cp redis:/data/dump.rdb .
            - task: tail-servers-logs
            - docker run --rm
                --network host
                --env-file common/env/{{.VIDEOSDB_CONFIG}}.txt
                {{if .LOGLEVEL}} -e LOGLEVEL={{.LOGLEVEL}} {{end}}
                {{.REPO}}backend-{{.BRANCH_NAME}}:latest
                run main
                    --check-for-new-videos
                    --enable-transcripts
                    --enable-twitter-publishing
                    --export-to-emulator-host {{.FIRESTORE_EMULATOR}}



    run-frontend:
        run: once
        cmds:
            - date
            - docker run --rm
                --network host
                --env-file common/env/{{.VIDEOSDB_CONFIG}}.txt
                -e FIRESTORE_EMULATOR_HOST={{.FIRESTORE_EMULATOR}}
                -e GOOGLE_APPLICATION_CREDENTIALS=common/keys/{{.VIDEOSDB_CONFIG}}.json
                {{.REPO}}frontend-{{.BRANCH_NAME}}:latest
                yarn run-s generate deploy



    generate-with-cache:
        deps: [download-cache]
        cmds:
            - defer: {task: upload-cache}
            - task: generate



    generate:
        cmds:
            - task: run-backend
            - task: run-frontend



    push:
        internal: true
        cmds:
            - date
            - docker push -q {{.REPO}}{{.IMAGE}}-{{.BRANCH_NAME}}:{{.REVISION_ID}}
            - docker push -q {{.REPO}}{{.IMAGE}}-{{.BRANCH_NAME}}:latest


    push-frontend:
        run: once
        cmds:
            - task: push
              vars:
                IMAGE: frontend


    push-backend:
        run: once
        cmds:
            - task: push
              vars:
                IMAGE: backend

    push-all:
        run: once
        cmds:
            - task: push-backend
            - task: push-frontend

    build-and-push-other-images:
        deps: [init-gcp]
        run: once
        cmds:
            - REPO={{.REGISTRY}} docker compose build {{.TEST_SERVERS}}
            - REPO={{.REGISTRY}} docker compose push {{.TEST_SERVERS}}
            - docker build utils/builder -t {{.REGISTRY}}videosdb-builder
            - docker push {{.REGISTRY}}videosdb-builder

    deploy-only-nithyananda:
        deps: [init-gcp]
        cmds:
            - docker pull {{.REGISTRY}}frontend-{{.BRANCH_NAME}}:latest
            - docker run --rm
                --env-file common/env/nithyananda.txt
                -e GOOGLE_APPLICATION_CREDENTIALS=common/keys/nithyananda.json
                {{.REGISTRY}}frontend-{{.BRANCH_NAME}}:latest
                yarn run-s generate deploy

    tests:
        cmds:
            - task: unittests
            - task: end2end-tests

    default:
        deps: [build-all]
        cmds:
            - task: tests
            - env

# local-only, non-docker commands:

    local-prepare:
        sudo npm install --global yarn;
        cd backend && poetry install; cd -; 
        cd frontend && yarn install; cd -; 
        sudo npm install --global firebase-tools;
        cd common/firebase && firebase setup:emulators:firestore && firebase setup:emulators:ui; cd -;

    local-unittests-backend:
        cd backend &&
        PYTHONDEVMODE=1
        FIRESTORE_EMULATOR_HOST={{.FIRESTORE_EMULATOR}}
            poetry run python -m unittest -v; cd ..

    local-unittests-frontend:
        cd frontend && yarn test

    local-unittests:
        deps: [local-unittests-backend, local-unittests-frontend]

    local-run:
        - task: tail-servers-logs
        - task: local-run-backend
        - task: local-run-frontend

    local-run-backend:
        cmds:
            - cd backend && 
                LOGLEVEL=DEBUG
                DEBUG=1
                YOUTUBE_API_URL=http://127.0.0.1:43783/youtube/v3
                FIRESTORE_EMULATOR_HOST={{.FIRESTORE_EMULATOR}}
                poetry run main -c --dotenv ../common/env/testing.txt


    local-run-frontend:
        cmds:
            - 
            - cd frontend && FIRESTORE_EMULATOR_HOST={{.FIRESTORE_EMULATOR}}
                yarn generate --dotenv ../common/env/testing.txt
            - cd frontend && yarn start --dotenv ../common/env/testing.txt

        vars:
            FIRESTORE_EMULATOR_HOST: .FIRESTORE_EMULATOR

    local-dev-frontend:
        cd frontend &&
        FIRESTORE_EMULATOR_HOST={{.FIRESTORE_EMULATOR}}
        yarn dev -t spa --dotenv ../common/env/testing.txt; cd ..

    local-ipython-shell: backend/utils/ipythonshell.sh

    local-prepare-servers: sudo systemctl start redis-server && cd common/firebase && firebase emulators:start --project demo-project; cd ../..

    local-push-to-prod: git checkout prod && git merge master && git push && git checkout master



# cloud build trigger tasks. Task names must match with the trigger names in the GCP console

    build-and-push-master:
        cmds:
            - task: build-all
            - task: unittests
            - task: push-all

    build-and-push-prod:
        cmds:
            - task: build-all
            - task: unittests
            - task: end2end-tests
            - task: push-all

    tests-end2end-master:
        cmds:
            - task: end2end-tests

    tests-end2end-prod:
        cmds:
            - task: end2end-tests

    generate-testing:
        cmds:
            - task: generate-with-cache
        preconditions:
            - test {{.VIDEOSDB_CONFIG}}

    generate-sadhguru:
        cmds:
            - task: generate-with-cache
        preconditions:
            - test {{.VIDEOSDB_CONFIG}}

    generate-nithyananda:
        cmds:
            - task: generate-with-cache
        preconditions:
            - test {{.VIDEOSDB_CONFIG}}


