version: '3'
env:
    DOCKER_PASSWORD: 5@fs@i@58Zp6wfiH
    REPO_PROJECT: worpdress-279321
    REPO: '{{if .BUILD_ID }}gcr.io/{{.REPO_PROJECT}}/{{end}}'
    BRANCH:
        sh: git branch --show-current
    REVISION_ID:
        sh: git rev-parse HEAD
    ENV_FILE: 'common/env/{{default "testing" .VIDEOSDB_CONFIG}}.txt'

tasks:
    init-local:
        cmds:
            - pgrep docker > /dev/null || sudo service docker start

    init-gcp:
        cmds:
            - echo {{.DOCKER_PASSWORD}} | docker login --username eelis --password-stdin
            - docker login gcr.io

    build:
        internal: true
        cmds:
            # pull an image to --cache-from
            - cmd: '{{if .BUILD_ID }} docker pull {{.REPO}}{{.IMAGE}}-{{.BRANCH}}:latest{{end}}'
              ignore_errors: true

            - docker build
                -t {{.REPO}}{{.IMAGE}}-{{.BRANCH}}:{{.REVISION_ID}}
                -t {{.REPO}}{{.IMAGE}}-{{.BRANCH}}:latest
                --cache-from {{.REPO}}{{.IMAGE}}-{{.BRANCH}}:latest
                {{.IMAGE}}

    run:
        internal: true
        cmds:
            - docker run --network host --env-file common/env/{{.ENV_FILE}}.txt {{.REPO}}{{.IMAGE}}-{{.BRANCH}}:latest {{.ARGS}}


    build-backend:
        run: once
        cmds:
            - task: build
              vars:
                IMAGE: backend

    build-frontend:
        run: once
        cmds:
            - task: build
              vars:
                IMAGE: frontend

    start-test-servers:
        run: once
        cmds:
            - docker compose build --pull
            - docker compose up --detach


    unittests-frontend:
        run: once
        deps:  [build-frontend]
        cmds:
            - task: run
              vars:
                IMAGE: frontend
                ENV_FILE: testing
                ARGS: yarn test

    unittests-backend:
        run: once
        deps:  [start-test-servers, build-backend]
        cmds:
            - task: run
              vars:
                IMAGE: backend
                ENV_FILE: testing
                ARGS: run python -m unittest

    unittests:
        run: once
        deps: [unittests-backend, unittests-frontend]

    end2end-tests:
        run: once
        deps: [build-frontend, build-backend, start-test-servers]
        cmds:
            - task: start-test-servers
            - task: run
              vars:
                IMAGE: backend
                ENV_FILE: testing
                ARGS: run main -c -e
            - task: run
              vars:
                IMAGE: frontend
                ENV_FILE: testing
                ARGS: yarn generate


    generate:
        run: once
        deps: [build-frontend, build-backend]
        cmds:
            - docker run
                --name downloader
                --env-file common/env/{{.VIDEOSDB_CONFIG}}.txt
                {{.REPO}}frontend-{{.BRANCH}}:latest
                run main -c
            - docker run
                --name generate
                --env-file common/env/{{.VIDEOSDB_CONFIG}}.txt
                {{.REPO}}backend-{{.BRANCH}}:latest
                yarn generate
            - docker cp
                generate:/app/dist frontend/
            - docker run
                -e GOOGLE_APPLICATION_CREDENTIALS=backend/videosdb/keys/{{.VIDEOSDB_CONFIG}}.json
                {{.REPO}}firebase deploy
                --project {{.FIREBASE_PROJECT}}
                --only=hosting

    push:
        internal: true
        cmds:
            - docker push {{.REPO}}{{.IMAGE}}-{{.BRANCH}}:{{.REVISION_ID}}
            - docker push {{.REPO}}{{.IMAGE}}-{{.BRANCH}}:latest


    push-frontend:
        deps: [build-frontend]
        run: once
        cmds:
            - task: push
              vars:
                IMAGE: frontend


    push-backend:
        deps: [build-backend]
        run: once
        cmds:
            - task: push
              vars:
                IMAGE: backend



