runtime: python39
env_variables:
  DATABASE_URL: postgres://postgres:TBSV96364xXi2JeWZiVibnbGczFNg@//cloudsql/worpdress-279321:asia-south1:db3/postgres

automatic_scaling:
  max_instances: 9

handlers:

- url: /api/.*
  script: auto

- url: /static
  static_dir: static/

- url: /
  static_files: dist/index.html
  upload: dist/index.html

- url: /(.*)/$
  static_files: dist/\1/index.html
  upload: dist/.*/index.html

- url: /
  static_dir: dist/