runtime: python39
env_variables:
  DATABASE_URL: psql://postgres:TBSV96364xXi2JeWZiVibnbGczFNg@db.sadhguru.digital:5432/postgres

# automatic_scaling:
#   max_instances: 18

#entrypoint: gunicorn -b :$PORT main:app

handlers:

- url: /api/.*
  script: auto

- url: /static
  static_dir: static/

- url: /
  static_files: dist/index.html
  upload: dist/index.html

- url: /(.*)/$
  static_files: dist/\1/index.html
  upload: dist/.*/index.html

- url: /
  static_dir: dist/