runtime: python39
env_variables:
  DATABASE_URL: postgres://postgres:TBSV96364xXi2JeWZiVibnbGczFNg@//cloudsql/worpdress-279321:asia-south1:db2/postgres
handlers:

- url: /api/.*
  script: auto

# This configures Google App Engine to serve the files in the app's static
# directory.

- url: /
  static_files: dist/index.html
  upload: dist/index.html

- url: /((.*\/)*[^\/]+\.[^\/]+)$
  static_files: dist/\1
  upload: dist/.*

- url: /(.*)$
  static_files: dist/\1/index.html
  upload: dist/.*/index.html