<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit" Version="2.5.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.5.3" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.1" />
    <PackageReference Include="RichardSzalay.MockHttp" Version="7.0.0" />
    <PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="9.0.0" />
    <ProjectReference Include="../../src/VideosDb/VideosDb.fsproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="UtilsTests.fs" />
    <Compile Include="DownloaderTests.fs" />
    <Compile Include="IpfsTests.fs" />
    <Compile Include="PublisherTests.fs" />
    <Compile Include="IntegrationTests.fs" />
    <Compile Include="Tests.fs" />
  </ItemGroup>

</Project>
