"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 2.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

from autologging import TRACE
import os
import hashlib
import environ
import sys


# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '4!_fouo%ikguf72o=em+(v0m)pdo7^8ae*vw$xs9&+l-dsa#*u'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True if "VIDEOSDB_DEBUG" in os.environ else False

ALLOWED_HOSTS = ["*"]

CORS_ORIGIN_ALLOW_ALL = True

env = environ.Env(DEBUG=(bool, False))
env_file = os.path.join(BASE_DIR, ".env")

if os.path.isfile(env_file):
    # Use a local secret file, if provided

    env.read_env(env_file)

# Application definition

INSTALLED_APPS = [
    "test_without_migrations",
    "videosdb.apps.VideosdbConfig",
    "rest_framework",
    "django_extensions",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'django_filters',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # 'django.middleware.cache.UpdateCacheMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.cache.FetchFromCacheMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.gzip.GZipMiddleware'
]

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'project.wsgi.application'

# For Google CLoud App Engine:
# Use django-environ to parse the connection string
DATABASES = {
    "default":
        env.db_url(
            "DATABASE_URL",
            default="psql://postgres:TBSV96364xXi2JeWZiVibnbGczFNg@localhost:5431/postgres"
        ),

}
#DATABASES["default"]["CONN_MAX_AGE"] = None

# if os.getenv("USE_CLOUD_SQL_AUTH_PROXY", None):
#     DATABASES["default"]["HOST"] = "127.0.0.1"
#     DATABASES["default"]["PORT"] = 5432


# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'my_cache_table',
        'TIMEOUT': 7776000,  # 3 months in seconds

        "OPTIONS": {
            'MAX_ENTRIES': 2147483647,  # max int32
        }
    }
}

#
# CACHES = {
#     'default': {
#         'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
#         'LOCATION': 'DataFlair',
#     }
# }
# # Key in `CACHES` dict
# CACHE_MIDDLEWARE_ALIAS = 'default'

# # Additional prefix for cache keys
# CACHE_MIDDLEWARE_KEY_PREFIX = ''

# # Cache key TTL in seconds
# CACHE_MIDDLEWARE_SECONDS = 600

# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

CORS_ORIGIN_WHITELIST = [
    'http://localhost:8080',
    'http://localhost:3000'
]

REST_FRAMEWORK = {
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    "DEFAULT_PERMISSION_CLASSES":   [
        "rest_framework.permissions.AllowAny"
    ]
}
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname}\t{asctime}:{name}.{funcName} ({filename}:{lineno:d}): {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname}\t{message}',
            'style': '{',
        },
    },
    'handlers': {
        # 'file': {
        #     'class': 'logging.handlers.RotatingFileHandler',
        #     'maxBytes': 1000000,
        #     "backupCount": 10,
        #     'filename': 'logs/videosdb.log',
        #     'formatter': 'verbose'
        # },
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
            'stream': sys.stderr
        }
    },
    'loggers': {
        'videosdb': {
            'handlers': ['console'],
            'level': os.environ.get("LOGLEVEL", "WARNING"),
            'propagate': False,
        },
        "property_manager": {
            'handlers': ['console'],
            "level": "WARNING",
            'propagate': False,
        },
        'django': {
            'handlers': ['console'],
            'level': os.environ.get("LOGLEVEL", "WARNING"),
            'propagate': False,
        },
        '': {
            'handlers': ['console'],
            'level': os.environ.get("LOGLEVEL", "WARNING"),
            'propagate': True
        }
    },
}

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = "static"
MEDIA_ROOT = "media"


IPFS_HOST = os.environ.get("IPFS_HOST", "127.0.0.1")
IPFS_PORT = os.environ.get("IPFS_PORT", 5001)

VIDEOSDB_DOMAIN = "sadhguru.digital"
VIDEOSDB_DNSZONE = "sadhguru"
YOUTUBE_CHANNEL = {
    "id": "UCcYzLCs3zrQIBVHYA1sK2sw",
    "name": "Sadhguru"
}
TRUNCATE_DESCRIPTION_AFTER = "#Sadhguru"
VIDEO_FILES_DIR = "/mnt/videos"


# YOUTUBE_KEY = "AIzaSyAL2IqFU-cDpNa7grJDxpVUSowonlWQFmU"  # works, primary
# YOUTUBE_KEY = "AIzaSyCRG-LiGKbn0ZFzNUU7qD3nzwkAw8I9Oa4"  # works
# YOUTUBE_KEY = "AIzaSyCvLLl93DvwWg5hnqizEbDz5hBE9fAmXnc" # doesn't work
# YOUTUBE_KEY = "AIzaSyBS_oLkjg3skPbC49VmPit3dPFPPnZDPRQ"
# YOUTUBE_KEY = "AIzaSyBV1J9SPIGKSpl5nxHdzwS6mx5aIFfjpXE"

# works, used for testing, responses in HAR file
YOUTUBE_KEY = "AIzaSyDM-rEutI1Mr6_b1Uz8tofj2dDlwcOzkjs"
