version: "3"
services:
  registry:
      restart: always
      image: registry:2
      environment:
        - REGISTRY_STORAGE_DELETE_ENABLED=true
      ports:
        - 5000:5000
      volumes:
        - /mnt/docker-registry:/var/lib/registry

