apiVersion: cloud-build-notifiers/v1
kind: SMTPNotifier
metadata:
  name: example-smtp-notifier
spec:
  notification:
    filter: build.status == Build.Status.FAILURE || build.status == Build.Status.INTERNAL_ERROR || build.status == Build.Status.TIMEOUT || build.status == Build.Status.CANCELLED || build.status == Build.Status.EXPIRED
    delivery:
      server: smtp.gmail.com
      port: "587"
      sender: johnnnnyha@gmail.com
      from: johnnnnyha@gmail.com
      recipients:
        - johnnnnyha@gmail.com
        # optional: more emails here
      password:
        secretRef: passsmtp
  secrets:
  - name: passsmtp
    value: projects/worpdress-279321/secrets/passsmtp/versions/latest