# Generated by Django 3.1.5 on 2021-02-02 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videosdb', 'regenerate_tags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Publication',
        ),
    ]
