# Generated by Django 3.1.6 on 2021-02-08 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videosdb', '0001_delete_publication'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='filename',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='ipfs_hash',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
