# Generated by Django 2.1.5 on 2019-02-11 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videosdb', '0002_auto_20190211_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='ipfs_hash',
            field=models.CharField(max_length=256, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='youtube_id',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
