# Generated by Django 3.2.8 on 2021-10-25 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videosdb', '0002_auto_20210208_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='related_videos',
            field=models.ManyToManyField(to='videosdb.Video'),
        ),
    ]
