# Generated by Django 3.2.8 on 2021-10-25 13:36

from django.db import migrations


def remove_untitled_videos(apps, schema_editor):
    Video = apps.get_model("videosdb", "Video")
    Video.objects.filter(title=None).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('videosdb', '0003_alter_video_related_videos'),
    ]

    operations = [
        migrations.RunPython(
            remove_untitled_videos, migrations.RunPython.noop
        )
    ]
