# Generated by Django 3.2.8 on 2021-10-25 13:48

from django.db import migrations


def remove_related_videos(apps, schema_editor):
    Video = apps.get_model("videosdb", "Video")

    for v in Video.objects.all():
        v.related_videos.clear()


class Migration(migrations.Migration):

    dependencies = [
        ('videosdb', '0004_auto_20211025_1336'),
    ]

    operations = [
        migrations.RunPython(
            remove_related_videos, migrations.RunPython.noop
        )
    ]
