# Generated by Django 2.1.5 on 2019-02-11 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videosdb', '0004_auto_20190211_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='channel_id',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
