# Generated by Django 3.2.8 on 2021-10-26 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videosdb', '0005_delete_related_videos_relations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=256, null=True, unique=True)),
                ('yt_data', models.JSONField()),
                ('yt_playlist_id', models.CharField(db_index=True, max_length=256, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='tag',
            name='videosdb_ta_slug_83848a_idx',
        ),
        migrations.RemoveField(
            model_name='video',
            name='added_date',
        ),
        migrations.RemoveField(
            model_name='video',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='video',
            name='channel_id',
        ),
        migrations.RemoveField(
            model_name='video',
            name='comment_count',
        ),
        migrations.RemoveField(
            model_name='video',
            name='definition',
        ),
        migrations.RemoveField(
            model_name='video',
            name='description',
        ),
        migrations.RemoveField(
            model_name='video',
            name='dislike_count',
        ),
        migrations.RemoveField(
            model_name='video',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='video',
            name='excluded',
        ),
        migrations.RemoveField(
            model_name='video',
            name='favorite_count',
        ),
        migrations.RemoveField(
            model_name='video',
            name='full_response',
        ),
        migrations.RemoveField(
            model_name='video',
            name='like_count',
        ),
        migrations.RemoveField(
            model_name='video',
            name='modified_date',
        ),
        migrations.RemoveField(
            model_name='video',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='video',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='video',
            name='title',
        ),
        migrations.RemoveField(
            model_name='video',
            name='uploader',
        ),
        migrations.RemoveField(
            model_name='video',
            name='view_count',
        ),
        migrations.RemoveField(
            model_name='video',
            name='yt_published_date',
        ),
        migrations.AddField(
            model_name='video',
            name='yt_data',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='playlist',
            name='videos',
            field=models.ManyToManyField(to='videosdb.Video'),
        ),
    ]
