# Generated by Django 3.2.9 on 2021-11-02 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videosdb', '0005_delete_related_videos_relations'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Video',
            new_name='PersistentVideoData',
        ),
        migrations.RemoveIndex(
            model_name='persistentvideodata',
            name='videosdb_vi_youtube_a742c5_idx',
        ),
        migrations.RemoveIndex(
            model_name='persistentvideodata',
            name='videosdb_vi_slug_9616f2_idx',
        ),
        migrations.RemoveIndex(
            model_name='persistentvideodata',
            name='videosdb_vi_id_63dbbd_idx',
        ),
        migrations.AddIndex(
            model_name='persistentvideodata',
            index=models.Index(fields=['youtube_id'], name='videosdb_pe_youtube_1748f0_idx'),
        ),
        migrations.AddIndex(
            model_name='persistentvideodata',
            index=models.Index(fields=['slug'], name='videosdb_pe_slug_e92769_idx'),
        ),
        migrations.AddIndex(
            model_name='persistentvideodata',
            index=models.Index(fields=['id'], name='videosdb_pe_id_6921d4_idx'),
        ),
    ]
