# Generated by Django 3.2.9 on 2021-11-02 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videosdb', '0006_rename_table'),
    ]

    operations = [
            migrations.RunSQL(
                sql="DROP INDEX videosdb_video_youtube_id_c662eeca_like;"),
            migrations.RunSQL(
                sql="DROP INDEX videosdb_video_slug_874d4564_like;")

    ]
