# Generated by Django 3.2.8 on 2021-10-31 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videosdb', '0006_auto_20211026_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersistentVideoData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transcript', models.TextField(null=True)),
                ('transcript_available', models.BooleanField(null=True)),
                ('ipfs_hash', models.CharField(max_length=256, null=True)),
                ('filename', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='video',
            name='videosdb_vi_youtube_a742c5_idx',
        ),
        migrations.RemoveIndex(
            model_name='video',
            name='videosdb_vi_slug_9616f2_idx',
        ),
        migrations.RemoveIndex(
            model_name='video',
            name='videosdb_vi_id_63dbbd_idx',
        ),
        migrations.RenameField(
            model_name='playlist',
            old_name='yt_playlist_id',
            new_name='youtube_id',
        ),
        migrations.RemoveField(
            model_name='video',
            name='filename',
        ),
        migrations.RemoveField(
            model_name='video',
            name='ipfs_hash',
        ),
        migrations.RemoveField(
            model_name='video',
            name='transcript',
        ),
        migrations.RemoveField(
            model_name='video',
            name='transcript_available',
        ),
    ]
