# Generated by Django 2.1.5 on 2019-02-11 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videosdb', '0006_auto_20190211_1810'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='abr',
        ),
        migrations.RemoveField(
            model_name='video',
            name='channel_url',
        ),
        migrations.RemoveField(
            model_name='video',
            name='description',
        ),
        migrations.RemoveField(
            model_name='video',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='video',
            name='ext',
        ),
        migrations.RemoveField(
            model_name='video',
            name='format',
        ),
        migrations.RemoveField(
            model_name='video',
            name='format_note',
        ),
        migrations.RemoveField(
            model_name='video',
            name='fulltitle',
        ),
        migrations.RemoveField(
            model_name='video',
            name='height',
        ),
        migrations.RemoveField(
            model_name='video',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='video',
            name='upload_date',
        ),
        migrations.RemoveField(
            model_name='video',
            name='uploader_url',
        ),
        migrations.RemoveField(
            model_name='video',
            name='view_count',
        ),
        migrations.RemoveField(
            model_name='video',
            name='width',
        ),
        migrations.AddField(
            model_name='video',
            name='full_response',
            field=models.CharField(max_length=4096, null=True),
        ),
    ]
