# Generated by Django 2.1.5 on 2019-02-11 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videosdb', '0007_auto_20190211_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='duration',
            field=models.IntegerField(null=True),
        ),
    ]
