# Generated by Django 3.2.9 on 2021-11-02 03:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videosdb', '0007_remove_dangling_migrations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_id', models.CharField(db_index=True, max_length=256, unique=True)),
                ('yt_data', models.JSONField()),
                ('slug', models.SlugField(max_length=256, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_id', models.CharField(max_length=16, unique=True)),
                ('yt_data', models.JSONField()),
                ('slug', models.SlugField(max_length=4096, null=True, unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='persistentvideodata',
            name='videosdb_pe_youtube_1748f0_idx',
        ),
        migrations.RemoveIndex(
            model_name='persistentvideodata',
            name='videosdb_pe_slug_e92769_idx',
        ),
        migrations.RemoveIndex(
            model_name='persistentvideodata',
            name='videosdb_pe_id_6921d4_idx',
        ),
        migrations.RemoveIndex(
            model_name='tag',
            name='videosdb_ta_slug_83848a_idx',
        ),
        migrations.RemoveField(
            model_name='persistentvideodata',
            name='added_date',
        ),
        migrations.RemoveField(
            model_name='persistentvideodata',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='persistentvideodata',
            name='channel_id',
        ),
        migrations.RemoveField(
            model_name='persistentvideodata',
            name='comment_count',
        ),
        migrations.RemoveField(
            model_name='persistentvideodata',
            name='definition',
        ),
        migrations.RemoveField(
            model_name='persistentvideodata',
            name='description',
        ),
        migrations.RemoveField(
            model_name='persistentvideodata',
            name='dislike_count',
        ),
        migrations.RemoveField(
            model_name='persistentvideodata',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='persistentvideodata',
            name='excluded',
        ),
        migrations.RemoveField(
            model_name='persistentvideodata',
            name='favorite_count',
        ),
        migrations.RemoveField(
            model_name='persistentvideodata',
            name='full_response',
        ),
        migrations.RemoveField(
            model_name='persistentvideodata',
            name='like_count',
        ),
        migrations.RemoveField(
            model_name='persistentvideodata',
            name='modified_date',
        ),
        migrations.RemoveField(
            model_name='persistentvideodata',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='persistentvideodata',
            name='related_videos',
        ),
        migrations.RemoveField(
            model_name='persistentvideodata',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='persistentvideodata',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='persistentvideodata',
            name='thumbnail',
        ),
        migrations.RemoveField(
            model_name='persistentvideodata',
            name='title',
        ),
        migrations.RemoveField(
            model_name='persistentvideodata',
            name='uploader',
        ),
        migrations.RemoveField(
            model_name='persistentvideodata',
            name='view_count',
        ),
        migrations.RemoveField(
            model_name='persistentvideodata',
            name='yt_published_date',
        ),
        migrations.AlterField(
            model_name='persistentvideodata',
            name='youtube_id',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.AddField(
            model_name='video',
            name='data',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='videosdb.persistentvideodata'),
        ),
        migrations.AddField(
            model_name='video',
            name='related_videos',
            field=models.ManyToManyField(to='videosdb.Video'),
        ),
        migrations.AddField(
            model_name='video',
            name='tags',
            field=models.ManyToManyField(to='videosdb.Tag'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='videos',
            field=models.ManyToManyField(to='videosdb.Video'),
        ),
    ]
