# Generated by Django 2.1.5 on 2019-02-12 07:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('videosdb', '0008_video_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='publish_date',
            new_name='published_date',
        ),
        migrations.AddField(
            model_name='video',
            name='added_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
