# Generated by Django 3.2.9 on 2021-11-02 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videosdb', '0008_auto_20211102_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persistentvideodata',
            name='youtube_id',
            field=models.CharField(db_index=True, max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='youtube_id',
            field=models.CharField(db_index=True, max_length=16, unique=True),
        ),
    ]
