# Generated by Django 2.1.5 on 2019-02-12 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videosdb', '0009_auto_20190212_0725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='thumbnail_url',
        ),
    ]
