# Generated by Django 3.1.4 on 2020-12-22 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videosdb', '0011_video_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='transcript',
            field=models.TextField(null=True),
        ),
    ]
