# Generated by Django 3.1.4 on 2020-12-23 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videosdb', '0012_video_transcript'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='sync_action',
            field=models.CharField(choices=[('keep', 'keep'), ('insert', 'insert'), ('update', 'update'), ('delete', 'delete')], default='keep', max_length=32),
        ),
    ]
