# Generated by Django 3.1.4 on 2020-12-23 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videosdb', '0016_auto_20201223_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='post_id',
            field=models.IntegerField(null=True),
        ),
    ]
