# Generated by Django 3.1.4 on 2020-12-24 12:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('videosdb', '0019_auto_20201224_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='post_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='publication',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 24, 12, 26, 8, 527407, tzinfo=utc)),
            preserve_default=False,
        )
    ]
