# Generated by Django 3.1.4 on 2020-12-29 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videosdb', '0021_auto_20201225_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail_id',
            field=models.IntegerField(null=True),
        ),
    ]
