# Generated by Django 3.1.4 on 2020-12-29 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videosdb', '0024_auto_20201229_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='thumbnail_id',
        ),
        migrations.AddField(
            model_name='publication',
            name='thumbnail_id',
            field=models.IntegerField(null=True),
        ),
    ]
