# Generated by Django 3.1.4 on 2021-01-06 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videosdb', '0032_auto_20210106_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='published_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='Publication',
        ),
    ]
