# Generated by Django 3.1.4 on 2021-01-07 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videosdb', '0034_auto_20210106_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='comment_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='definition',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='dislike_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='favorite_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='like_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='view_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='duration',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
