# Generated by Django 3.1.4 on 2021-01-07 02:24

from django.db import migrations, models
from django.db.models.indexes import Index
from django.db.migrations import AddIndex


class Migration(migrations.Migration):

    dependencies = [
        ('videosdb', '0035_auto_20210107_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='youtube_id',
            field=models.CharField(db_index=True, max_length=16, unique=True),
        ),
        AddIndex('video', Index(
            fields=['youtube_id'], name='youtube_id_index')),
        AddIndex('video', Index(
            fields=['slug'], name='slug_index')),
        AddIndex('tag', Index(
            fields=['slug'], name='tag_slug_index')),
        AddIndex('category', Index(
            fields=['slug'], name='category_slug_index')),
    ]
