# Generated by Django 3.1.5 on 2021-01-21 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videosdb', '0040_auto_20210114_1612'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={},
        ),
    ]
