# Generated by Django 3.1.5 on 2021-01-19 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videosdb', '0041_auto_20210117_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='related_videos',
            field=models.ManyToManyField(related_name='_video_related_videos_+', to='videosdb.Video'),
        ),
        migrations.AlterField(
            model_name='video',
            name='channel_id',
            field=models.CharField(max_length=256, null=True, verbose_name='channelId'),
        ),
        migrations.AlterField(
            model_name='video',
            name='comment_count',
            field=models.IntegerField(null=True, verbose_name='commentCount'),
        ),
        migrations.AlterField(
            model_name='video',
            name='definition',
            field=models.CharField(max_length=256, null=True, verbose_name='definition'),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='video',
            name='dislike_count',
            field=models.IntegerField(null=True, verbose_name='dislikeCount'),
        ),
        migrations.AlterField(
            model_name='video',
            name='duration',
            field=models.CharField(max_length=256, null=True, verbose_name='duration'),
        ),
        migrations.AlterField(
            model_name='video',
            name='favorite_count',
            field=models.IntegerField(null=True, verbose_name='favoriteCount'),
        ),
        migrations.AlterField(
            model_name='video',
            name='like_count',
            field=models.IntegerField(null=True, verbose_name='likeCount'),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(max_length=256, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='video',
            name='uploader',
            field=models.CharField(max_length=256, null=True, verbose_name='channelTitle'),
        ),
        migrations.AlterField(
            model_name='video',
            name='view_count',
            field=models.IntegerField(null=True, verbose_name='viewCount'),
        ),
        migrations.AlterField(
            model_name='video',
            name='yt_published_date',
            field=models.DateTimeField(null=True, verbose_name='publishedAt'),
        ),
    ]
