# Generated by Django 3.1.5 on 2021-01-20 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videosdb', '0042_auto_20210119_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='channel_id',
            field=models.CharField(help_text='channelId', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='comment_count',
            field=models.IntegerField(help_text='commentCount', null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='definition',
            field=models.CharField(help_text='definition', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='description',
            field=models.TextField(help_text='description', null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='dislike_count',
            field=models.IntegerField(help_text='dislikeCount', null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='duration',
            field=models.CharField(help_text='duration', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='favorite_count',
            field=models.IntegerField(help_text='favoriteCount', null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='like_count',
            field=models.IntegerField(help_text='likeCount', null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(help_text='title', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='uploader',
            field=models.CharField(help_text='channelTitle', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='view_count',
            field=models.IntegerField(help_text='viewCount', null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='yt_published_date',
            field=models.DateTimeField(help_text='publishedAt', null=True),
        ),
    ]
