# Generated by Django 3.1.5 on 2021-01-21 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videosdb', '0043_auto_20210120_0127'),
        ('videosdb', '0041_auto_20210121_1515'),
    ]

    operations = [
    ]
