# Generated by Django 3.1.5 on 2021-01-22 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videosdb', '0044_merge_20210121_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='transcript_available',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
