# Generated by Django 3.1.5 on 2021-01-22 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videosdb', '0045_video_transcript_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='transcript_available',
            field=models.BooleanField(null=True),
        ),
    ]
