# Generated by Django 3.1.5 on 2021-01-31 15:24
import json
from django.db import migrations
from uuslug import uuslug


def update_tags(apps, schemda_editor):
    Tag = apps.get_model("videosdb", "Tag")
    Video = apps.get_model("videosdb", "Video")
    Tag.objects.all().delete()

    for v in Video.objects.filter(excluded=False):
        if not v.full_response:
            continue
        info = json.loads(v.full_response)
        if "tags" in info:
            for tag in info["tags"]:
                tag_obj, created = Tag.objects.get_or_create(name=tag.lower())
                v.tags.add(tag_obj)
                v.save()

    for t in Tag.objects.all():
        if not t.slug and t.name:
            t.slug = uuslug(t.name, instance=t)
        t.save()


class Migration(migrations.Migration):

    dependencies = [
        ('videosdb', '0046_auto_20210122_1338'),
    ]

    operations = [
        migrations.RunPython(
            update_tags, reverse_code=migrations.RunPython.noop),
    ]
