version: "2.1"
services:
  ipfs:
    image: ghcr.io/linuxserver/ipfs
    container_name: ipfs
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
#    volumes:
#      - /var/opt/ipfs:/config
    ports:
      - 8081:80
      - 4001:4001
      - 5001:5001
      - 8080:8080
      - 8443:443 #optional
    restart: unless-stopped
